version: '3'
services:
  postgres:
    container_name: ZhongYao_PostgreSql
    image: postgres
    restart: always
    env_file:
      - .env.development
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'

  redis:
    container_name: ZhongYao_redis
    image: redis:latest
    env_file:
      - .env.development
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    command: ['redis-server', '--requirepass', $REDIS_PASSWORD]
